name: just_finance_app
description: Simple finances manager.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.8.3
  provider: ^6.0.5
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
