name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Build APK and Create Release
      uses: Dank-del/flutter-build-and-publish-action@v1
      
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
