on:
  push:
    branches:
      - main
      - dev
      

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: minor
          release_branch: main
          
      - name: Changelog
        uses: ardalanamini/auto-changelog@v4
        id  : changelog
        with:
            github-token            : ${{ secrets.TOKEN }}
            commit-types            : |
              feat: New Features
              fix: Bug Fixes
              build: Build System & Dependencies
              perf: Performance Improvements
              docs: Documentation
              test: Tests
              refactor: Refactors
              chore: Chores
              style: Code Style
              revert: Reverts
            default-commit-type     : Other Changes
            release-name            : v${{ steps.version.outputs.version }}
            release-name-prefix     : ""
            mention-authors         : true
            mention-new-contributors: true
            include-compare-link    : true
            include-pr-links        : true
            include-commit-links    : true
            semver                  : true
            use-github-autolink     : true

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        id  : release
        with:
          artifacts: "build/app/outputs/apk/release/*"
          #allowUpdates: true
          generateReleaseNotes: true
          body:  ${{ steps.changelog.outputs.changelog }}
          tag: ${{ steps.version.outputs.version }}
          token: ${{ secrets.TOKEN }}