on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Version
        run: |
          cat pubspec.yaml | grep version: | awk '{print $2}'
          echo "VERSION=$(cat pubspec.yaml | grep version: | awk '{print $2}')" >> $GITHUB_ENV
          echo $VERSION
        shell: bash

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: $VERSION
          token: ${{ secrets.TOKEN }}